# Generated by Django 5.0.6 on 2024-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_participant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
